theme: jekyll-theme-minimal
title: Depuis le 13 mars
description: Un projet citoyen dédié au suivi de la mise en oeuvre des mesures de prévention du harcèlement moral dans la fonction publique, prévues dans la loi de 2019-828 "loi de transformation de la fonction publique".
